version : "3.9"
services:
  flaskapp:
    build: .
    ports:
    - 5000:5000
    depends_on:
    - "db"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: postgres
        USE_POSTGRES: 'true'
    restart: always 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: secret
    restart: always



